databases:
  - name: feedback-db
    databaseName: feedback
    user: postgres

services:
  - type: web
    name: backend
    env: docker
    plan: free
    dockerfilePath: Dockerfile.backend
    envVars:
      - key: PGHOST
        fromDatabase: feedback-db
        property: host
      - key: PGPORT
        fromDatabase: feedback-db
        property: port
      - key: PGDATABASE
        fromDatabase: feedback-db
        property: database
      - key: PGUSER
        fromDatabase: feedback-db
        property: user
      - key: PGPASSWORD
        fromDatabase: feedback-db
        property: password
      - key: GROQ_API_KEY
        sync: false          # la añades tú en el panel
    ports:                   # Render autodetecta, pero lo declaramos
      - port: 8000

  - type: web
    name: frontend
    env: docker
    plan: free
    dockerfilePath: Dockerfile.frontend
    envVars:
      - key: BACKEND_URL
        value: https://backend.onrender.com    # Render lo genera al crear
    ports:
      - port: 8501
