services:
  # -------- BACKEND -------- #
  - type: web
    name: backend
    env: docker
    plan: free
    dockerfilePath: dockerfile.backend
    envVars:
      - key: PGHOST
        fromDatabase:
          name: feedback-db
          property: host
      - key: PGPORT
        fromDatabase:
          name: feedback-db
          property: port
      - key: PGDATABASE
        fromDatabase:
          name: feedback-db
          property: database
      - key: PGUSER
        fromDatabase:
          name: feedback-db
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: feedback-db
          property: password
      - key: GROQ_API_KEY    # la añadimos en el panel
        sync: false          # evita que render la escriba en el yaml

  # -------- FRONTEND -------- #
  - type: web
    name: frontend
    env: docker
    plan: free
    dockerfilePath: dockerfile.frontend
    envVars:
      # Render resuelve automáticamente http://backend:8000
      # gracias al DNS interno, así que no necesitas URL pública.
      - key: BACKEND_URL
        value: http://backend:8000
